package cn.cbdi.savecap.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.cbdi.savecap.Bean.ICardInfo;

import cn.cbdi.savecap.greendao.ICardInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig iCardInfoDaoConfig;

    private final ICardInfoDao iCardInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        iCardInfoDaoConfig = daoConfigMap.get(ICardInfoDao.class).clone();
        iCardInfoDaoConfig.initIdentityScope(type);

        iCardInfoDao = new ICardInfoDao(iCardInfoDaoConfig, this);

        registerDao(ICardInfo.class, iCardInfoDao);
    }
    
    public void clear() {
        iCardInfoDaoConfig.clearIdentityScope();
    }

    public ICardInfoDao getICardInfoDao() {
        return iCardInfoDao;
    }

}
