package cn.cbdi.savecap.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.cbdi.savecap.Bean.ICardInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ICARD_INFO".
*/
public class ICardInfoDao extends AbstractDao<ICardInfo, String> {

    public static final String TABLENAME = "ICARD_INFO";

    /**
     * Properties of entity ICardInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CardId = new Property(0, String.class, "cardId", true, "CARD_ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
    }


    public ICardInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ICardInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ICARD_INFO\" (" + //
                "\"CARD_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: cardId
                "\"NAME\" TEXT);"); // 1: name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ICARD_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ICardInfo entity) {
        stmt.clearBindings();
 
        String cardId = entity.getCardId();
        if (cardId != null) {
            stmt.bindString(1, cardId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ICardInfo entity) {
        stmt.clearBindings();
 
        String cardId = entity.getCardId();
        if (cardId != null) {
            stmt.bindString(1, cardId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public ICardInfo readEntity(Cursor cursor, int offset) {
        ICardInfo entity = new ICardInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // cardId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ICardInfo entity, int offset) {
        entity.setCardId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final String updateKeyAfterInsert(ICardInfo entity, long rowId) {
        return entity.getCardId();
    }
    
    @Override
    public String getKey(ICardInfo entity) {
        if(entity != null) {
            return entity.getCardId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ICardInfo entity) {
        return entity.getCardId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
